name: Feature Request
description: Suggest an idea for this module
title: "ENH: "
labels: [enhancement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality to this module
        - label: >
            Changing existing functionality in this module
        - label: >
            Removing existing functionality in this module
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve, e.g. "I wish I could use this module to ..."
      placeholder: >
        I wish I could use this module...
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using psudocode if relevant.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe and support the feature request.
